EC2: Transfer log of stderr to S3

diff --git a/ec2/setup_genlog.sh.in b/ec2/setup_genlog.sh.in
--- a/ec2/setup_genlog.sh.in
+++ b/ec2/setup_genlog.sh.in
@@ -1,8 +1,8 @@
-#!/bin/bash -xe
+#!/bin/bash -x
 #
 # ----------------------------------------------------------------------
 
-# exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
 # set environment variables
 AWS_ACCESS_KEY=<AWS_ACCESS_KEY>
@@ -31,17 +31,17 @@ chmod 666 ~/.aws/config
 # add GitHub to known_hosts
 ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
 
-# # add swipl repo
-# # -y automatically responds yes to all queries
-# # needed for non-interactive script
-# sudo apt-add-repository -y ppa:swi-prolog/devel
-# sudo apt-get -y update
+# add swipl repo
+# -y automatically responds yes to all queries
+# needed for non-interactive script
+sudo apt-add-repository -y ppa:swi-prolog/devel
+sudo apt-get -y update
 
-# # install git
-# sudo apt-get install -y git
-# sudo apt-get install -y swi-prolog
+# install git
+sudo apt-get install -y git
+sudo apt-get install -y swi-prolog
 
-# sudo apt-get -y upgrade
+sudo apt-get -y upgrade
 
 # ####################
 # ## Get GenLog     ##
@@ -71,28 +71,61 @@ echo "Done."
 # source job script
 GENLOG_JOB_SCRIPT=${GENLOG_ROOT}/ec2/job.sh
 GENLOG_JOB_OUT=${GENLOG_ROOT}/ec2/job.out
+GENLOG_JOB_LOG=${GENLOG_ROOT}/ec2/job.log
+GENLOG_JOB_ID=$( date +%s%3 ) # milliseconds since epoch
+LOG_PRE="GenLog Job ${GENLOG_JOB_ID}: "
 chmod +x ${GENLOG_JOB_SCRIPT}
 if [ ! -x ${GENLOG_JOB_SCRIPT} ]
 then
-    echo "Cannot execute GenLog ec2 job script: ${GENLOG_JOB_SCRIPT}" 
+    echo "$LOG_PRE: Cannot execute GenLog ec2 job script: ${GENLOG_JOB_SCRIPT}" 
 else
-    echo "Executing GenLog ec2 job script: ${GENLOG_JOB_SCRIPT}..."
-    echo "Time: $(date +%Y.%m.%d-%H.%M.%S)"
-    bash -x ${GENLOG_JOB_SCRIPT}
-    echo "GenLog ec2 job script, ${GENLOG_JOB_SCRIPT}, finished running."
-    echo "Time: $(date +%Y.%m.%d-%H.%M.%S)"
+    echo "$LOG_PRE: Executing GenLog ec2 job script: ${GENLOG_JOB_SCRIPT}..."
+    echo "$LOG_PRE: Time: $(date +%Y.%m.%d-%H.%M.%S)"
+    bash -x ${GENLOG_JOB_SCRIPT} 2> ${GENLOG_JOB_LOG}
+    echo "$LOG_PRE: GenLog ec2 job script, ${GENLOG_JOB_SCRIPT}, finished running."
+    echo "$LOG_PRE: Time: $(date +%Y.%m.%d-%H.%M.%S)"
 fi
 
+# Transfer data to S3
+S3_DATA_PATH=data
+S3_DATA_PRE="out_job_id_"
+S3_DATA_FILENAME="${S3_DATA_PRE}_${GENLOG_JOB_ID}"
+S3_DATA_URL="s3://${S3_BUCKET}/${S3_DATA_PATH}/${S3_DATA_FILENAME}"
+
+S3_LOG_DIR="logs/jobs"
+S3_LOG_PRE="log_job_id_"
+S3_LOG_FILENAME="${S3_LOG_PRE}_${GENLOG_JOB_ID}"
+S3_LOG_URL="s3://${S3_BUCKET}/${S3_DATA_PATH}/${S3_DATA_FILENAME}"
+
+S3_LOG_URL="s3://${S3_BUCKET}/${S3_DATA_PATH}/${S3_DATA_FILENAME}"
+
+
+# upload job.out to S3
 if [ ! -r ${GENLOG_JOB_OUT} ]
 then
-    echo "Cannot find output of GenLog ec2 job script: ${GENLOG_JOB_OUT}"
+    echo "$LOG_PRE: Cannot find output of GenLog ec2 job script: ${GENLOG_JOB_OUT}"
+        
 else
-    t=$( date "+%Y-%m-%d-%HH-%MM-%SS" )
-    echo "Uploading job.out data to S3 bucket..."
-    aws s3 cp ${GENLOG_JOB_OUT} "s3://${S3_BUCKET}/data/out_$t"
+    echo "$LOG_PRE: Uploading job.out data to S3 bucket..."
+    aws s3 cp ${GENLOG_JOB_OUT} ${S3_DATA_URL}
     if [ $? -eq 0 ]; then
-        echo "Data transfer succeeded."
+        echo "$LOG_PRE: Data transfer succeeded."
     else
-        echo "Data transfer failed."
+        echo "$LOG_PRE: Data transfer failed."
+    fi
+fi
+
+# upload job.log to S3
+if [ ! -r ${GENLOG_JOB_LOG} ]
+then
+    echo "$LOG_PRE: Cannot find log file: ${GENLOG_JOB_LOG}"
+        
+else
+    echo "$LOG_PRE: Uploading log file  to S3 bucket..."
+    aws s3 cp ${GENLOG_JOB_LOG} ${S3_LOG_URL}
+    if [ $? -eq 0 ]; then
+        echo "$LOG_PRE: Data transfer succeeded."
+    else
+        echo "$LOG_PRE: Data transfer failed."
     fi
 fi
